In [30]:
pip install lxml

Requirement already satisfied: lxml in c:\users\aaron\appdata\local\programs\python\python312\lib\site-packages (6.1.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

## Exercise set 5

In [31]:
import pandas as pd
import requests
from bs4 import BeautifulSoup

# Exercise 1

In [32]:
# Load the DataFrame.
df_json = pd.read_json("simple.json")

# Display the DataFrame
df_json

,id,brand,model,year,owned_by,acquired,price
0,1,Chrysler,Voyager,2001,Wolff-Trantow,28/12/2016,11565
1,2,Volkswagen,Jetta,1995,"Schuppe, Pfeffer and Klein",20/4/2016,52431
2,3,Porsche,Cayenne,2005,Mante Group,11/6/2020,75552
3,4,Porsche,928,1994,Wisozk Group,17/6/2019,30331
4,5,Mercedes-Benz,SL-Class,2007,Schiller-Littel,20/7/2018,62385
...,...,...,...,...,...,...,...
95,96,Dodge,Ram 1500 Club,2000,Schneider-Donnelly,28/9/2016,56256
96,97,GMC,Yukon XL 2500,2001,"Powlowski, Lemke and Wiza",19/4/2016,50163
97,98,Chevrolet,Sportvan G20,1992,"O'Keefe, Rogahn and Gleichner",1/6/2019,8577
98,99,Mitsubishi,3000GT,1993,Hoppe-Kunde,29/12/2018,23180
99,100,Chevrolet,TrailBlazer,2002,Wunsch-Friesen,14/11/2018,76830

# Exercise 2

In [ ]:
# Load the DataFrame.
df_xml = pd.read_xml("simple.xml", xpath="//car")

# Squeeze.
series_xml = df_xml.squeeze()

# Show the result.
series_xml

id                                   1
brand                       Oldsmobile
model                           Aurora
year                              2003
owned_by    Herzog, Rodriguez and Howe
acquired                    21/10/2016
price                            32571
Name: 0, dtype: object

# Exercise 3

In [ ]:
# Let's fetch the data from the API.
url = "https://edu.frostbit.fi/api/events/en"
response = requests.get(url)
data = response.json()

# Json phase
df_api = pd.json_normalize(
    data,
    record_path=["categories"],
    meta=[
        "id",
        "name",
        ["address", "street"],
        ["address", "city"],
        ["address", "zip"],
    ],
    errors="ignore",
    )

# Let's rename the columns to make them more readable.
df_api = df_api.rename(columns={"address.street": "street", "address.city": "city", "address.zip": "zip"})

# Show the results.
print(df_api.head())
df_api

                       0   id                    name street city  zip
0            exhibitions  NaN  Atlases of The Mariner    NaN  NaN  NaN
1      maritime helsinki  NaN  Atlases of The Mariner    NaN  NaN  NaN
2            exhibitions  NaN  Atlases of The Mariner    NaN  NaN  NaN
3      maritime helsinki  NaN  Atlases of The Mariner    NaN  NaN  NaN
4  children (age groups)  NaN        Chess tournament    NaN  NaN  NaN

,0,id,name,street,city,zip
0,exhibitions,NaN,Atlases of The Mariner,NaN,NaN,NaN
1,maritime helsinki,NaN,Atlases of The Mariner,NaN,NaN,NaN
2,exhibitions,NaN,Atlases of The Mariner,NaN,NaN,NaN
3,maritime helsinki,NaN,Atlases of The Mariner,NaN,NaN,NaN
4,children (age groups),NaN,Chess tournament,NaN,NaN,NaN
5,cultural events,NaN,Chess tournament,NaN,NaN,NaN
6,games,NaN,Chess tournament,NaN,NaN,NaN
7,hobbies,NaN,Chess tournament,NaN,NaN,NaN
8,kilo,NaN,Chess tournament,NaN,NaN,NaN
9,leppävaara,NaN,Chess tournament,NaN,NaN,NaN
10,libraries,NaN,Chess tournament,NaN,NaN,NaN
11,lintuvaara,NaN,Chess tournament,NaN,NaN,NaN
12,young people,NaN,Chess tournament,NaN,NaN,NaN
13,craft skills,NaN,Art exhibition: Pikkukirjojen maailmat,NaN,NaN,NaN
14,cultural events,NaN,Art exhibition: Pikkukirjojen maailmat,NaN,NaN,NaN
15,exhibitions,NaN,Art exhibition: Pikkukirjojen maailmat,NaN,NaN,NaN
16,fine arts,NaN,Art exhibition: Pikkukirjojen maailmat,NaN,NaN,NaN
17,libraries,NaN,Art exhibition: Pikkukirjojen maailmat,NaN,NaN,NaN
18,mankkaa,NaN,Art exhibition: Pikkukirjojen maailmat,NaN,NaN,NaN
19,pohjois-tapiola,NaN,Art exhibition: Pikkukirjojen maailmat,NaN,NaN,NaN
20,tapiola,NaN,Art exhibition: Pikkukirjojen maailmat,NaN,NaN,NaN
21,westend,NaN,Art exhibition: Pikkukirjojen maailmat,NaN,NaN,NaN
22,architecture,NaN,Visions of Alvar Aalto – Finlandia Exhibition,NaN,NaN,NaN
23,design,NaN,Visions of Alvar Aalto – Finlandia Exhibition,NaN,NaN,NaN
24,design (artistic creation),NaN,Visions of Alvar Aalto – Finlandia Exhibition,NaN,NaN,NaN
25,exhibitions,NaN,Visions of Alvar Aalto – Finlandia Exhibition,NaN,NaN,NaN
26,concerts,NaN,Arabia soi: Night of the Guitarists,NaN,NaN,NaN
27,cultural events,NaN,Arabia soi: Night of the Guitarists,NaN,NaN,NaN
28,guitar music,NaN,Arabia soi: Night of the Guitarists,NaN,NaN,NaN
29,music,NaN,Arabia soi: Night of the Guitarists,NaN,NaN,NaN
30,ballet (art forms),NaN,Sequences - Evening of Choreography and Dance,NaN,NaN,NaN
31,contemporary dance,NaN,Sequences - Evening of Choreography and Dance,NaN,NaN,NaN
32,dance (performing arts),NaN,Sequences - Evening of Choreography and Dance,NaN,NaN,NaN
33,hip hop culture,NaN,Sequences - Evening of Choreography and Dance,NaN,NaN,NaN
34,ballet (art forms),NaN,Sequences - Evening of Choreography and Dance,NaN,NaN,NaN
35,contemporary dance,NaN,Sequences - Evening of Choreography and Dance,NaN,NaN,NaN
36,dance (performing arts),NaN,Sequences - Evening of Choreography and Dance,NaN,NaN,NaN
37,hip hop culture,NaN,Sequences - Evening of Choreography and Dance,NaN,NaN,NaN
38,art,NaN,Acrylic Pouring Workshop,NaN,NaN,NaN
39,cultural events,NaN,Acrylic Pouring Workshop,NaN,NaN,NaN
40,fine arts,NaN,Acrylic Pouring Workshop,NaN,NaN,NaN
41,participation,NaN,Acrylic Pouring Workshop,NaN,NaN,NaN
42,craft skills,NaN,Exhibition: Monster Mash,NaN,NaN,NaN
43,cultural events,NaN,Exhibition: Monster Mash,NaN,NaN,NaN
44,exhibitions,NaN,Exhibition: Monster Mash,NaN,NaN,NaN
45,fine arts,NaN,Exhibition: Monster Mash,NaN,NaN,NaN
46,libraries,NaN,Exhibition: Monster Mash,NaN,NaN,NaN
47,mankkaa,NaN,Exhibition: Monster Mash,NaN,NaN,NaN
48,pohjois-tapiola,NaN,Exhibition: Monster Mash,NaN,NaN,NaN
49,tapiola,NaN,Exhibition: Monster Mash,NaN,NaN,NaN
50,westend,NaN,Exhibition: Monster Mash,NaN,NaN,NaN
51,conversation,NaN,Finnish language café,NaN,NaN,NaN
52,language cafés,NaN,Finnish language café,NaN,NaN,NaN
53,participation,NaN,Finnish language café,NaN,NaN,NaN
54,art,NaN,Diving Beneath The Surface,NaN,NaN,NaN
55,cultural events,NaN,Diving Beneath The Surface,NaN,NaN,NaN
56,exhibitions,NaN,Diving Beneath The Surface,NaN,NaN,NaN
57,fine arts,NaN,Diving Beneath The Surface,NaN,NaN,NaN

# Exercise 4

In [ ]:
# Let's fetch the data from wikipedia.
url_rovaniemi = "https://en.wikipedia.org/wiki/Rovaniemi"
response = requests.get(url_rovaniemi)
soup = BeautifulSoup(response.content, "html.parser")


# Coordinates phase
coords_tag = soup.find("span",{"id": "coordinates"})

if coords_tag:
    coords = coords_tag.get_text(strip=True)
    print("Coordinates:", coords)
else: 
    print("Coordinates not found.")




# Nickname phase
nicknames = None
infobox = soup.find("table", {"class": "infobox"})

if infobox:
    for row in infobox.find_all("tr"):
        header = row.find("th")
        if header and "Nickname" in header.get_text():
            value_cell = row.find("td")
            if value_cell:
                nicknames = value_cell.get_text(strip=True)
                break

print("Nicknames:", nicknames)

Coordinates not found.
Nicknames: None

# Exercise 6

In [ ]:
# Load both CSV files.
df_coffee = pd.read_csv("coffee_sales.csv")
df_temps = pd.read_csv("temperatures_fixed.csv")

# Let's merge the DataFrames.
df_merged = pd.merge(
    df_coffee,
    df_temps,
    on = "Date",
    how = "left"
)

# Show the results.
print(df_merged.head())

        Date  Sales  Target_sales  Total_expenses  Temperature (C)
0  1.10.2012    122            90              76        19.822917
1  1.10.2012    123            90              45        19.822917
2  2.10.2012    107            90              36        19.020602
3  3.10.2012     94           100              21        15.820139
4  4.10.2012    182            80              54        15.110648