In [1]:
import numpy as np
import pandas as pd

# let's see what the data says
df = pd.read_csv('loans.csv')
df.head()

,Loan ID,Loan Status,Current Loan Amount,Term,Credit Score,Annual Income,Home Ownership,Purpose,Monthly Debt,Years of Credit History,Number of Open Accounts,Number of Credit Problems,Current Credit Balance,Maximum Open Credit,Bankruptcies
0,14dd8831-6af5-400b-83ec-68e61888a048,Fully Paid,445412.0,Short Term,709.0,1167493.0,Home Mortgage,Home Improvements,5214.74,17.2,6.0,1.0,228190.0,416746.0,1.0
1,4eed4e6a-aa2f-4c91-8651-ce984ee8fb26,Fully Paid,99999999.0,Short Term,741.0,2231892.0,Own Home,Debt Consolidation,29200.53,14.9,18.0,1.0,297996.0,750090.0,0.0
2,77598f7b-32e7-4e3b-a6e5-06ba0d98fe8a,Fully Paid,347666.0,Long Term,721.0,806949.0,Own Home,Debt Consolidation,8741.90,12.0,9.0,0.0,256329.0,386958.0,0.0
3,89d8cb0c-e5c2-4f54-b056-48a645c543dd,Charged Off,206602.0,Short Term,7290.0,896857.0,Home Mortgage,Debt Consolidation,16367.74,17.3,6.0,0.0,215308.0,272448.0,0.0
4,273581de-85d8-4332-81a5-19b04ce68666,Fully Paid,217646.0,Short Term,730.0,1184194.0,Home Mortgage,Debt Consolidation,10855.08,19.6,13.0,1.0,122170.0,272052.0,1.0

In [20]:
# Let's filter out exceedingly comical loans
df = df[df["Current Loan Amount"] < 9999999]

In [3]:
# Let's see what loan(s) have the highest credit balance 
df.nlargest(1, "Current Credit Balance")

,Loan ID,Loan Status,Current Loan Amount,Term,Credit Score,Annual Income,Home Ownership,Purpose,Monthly Debt,Years of Credit History,Number of Open Accounts,Number of Credit Problems,Current Credit Balance,Maximum Open Credit,Bankruptcies
12459,c194cb68-1c4d-4bba-8433-98cf4e0f357d,Charged Off,762850.0,Short Term,7320.0,7529320.0,Home Mortgage,other,205801.35,32.5,28.0,0.0,32878968.0,98627914.0,0.0

In [4]:
# Let's see which loan has the lowest annual income
df.nsmallest(1, "Annual Income")

,Loan ID,Loan Status,Current Loan Amount,Term,Credit Score,Annual Income,Home Ownership,Purpose,Monthly Debt,Years of Credit History,Number of Open Accounts,Number of Credit Problems,Current Credit Balance,Maximum Open Credit,Bankruptcies
48729,fdda52f3-bbfa-45da-80b5-2bd9b68638ed,Charged Off,30448.0,Short Term,736.0,76627.0,Rent,Debt Consolidation,845.5,9.5,8.0,0.0,28177.0,147598.0,0.0

In [5]:
# Let's see the min, max and mean of current loans.
pd.set_option('display.float_format', '{:.2f}'.format)
df["Current Loan Amount"].describe()

# Min is 15422.00
# Max is 789250.00
# And mean is 312122.30

count    58893.00
mean    312122.30
std     185174.86
min      15422.00
25%     172876.00
50%     267454.00
75%     432432.00
max     789250.00
Name: Current Loan Amount, dtype: float64

In [10]:
# Let's create a new field:
df["Actual Annual Income"] = df["Annual Income"] - 12 * df["Monthly Debt"]

In [12]:
# How many loans are "Long Term"?
df["Term"].value_counts()

# Answer: 16752

Term
Short Term    42141
Long Term     16752
Name: count, dtype: int64

In [13]:
# What are the 3 most common loan purposes?
df["Purpose"].value_counts().head(3)

# Debt Consolidation, Other and Home Improvements

Purpose
Debt Consolidation    46474
other                  3570
Home Improvements      3397
Name: count, dtype: int64

In [14]:
# How many unique home ownerships are there?
df["Home Ownership"].unique()

<StringArray>
['Home Mortgage', 'Own Home', 'Rent']
Length: 3, dtype: str