In [1]:
# Let's load the data
import pandas as pd

df = pd.read_csv("purchases.csv")
df.head()

,Purchase Date,Purchase Order Number,Acquisition Type,Acquisition Method,Department Name,Supplier Name,Item Name,Item Description,Quantity,Unit Price,Total Price,Commodity Title,Class Title,Family Title,Segment Title
0,08/31/2012,4500149558,Other Goods,Formal Competitive,"Corrections and Rehabilitation, Department of",Fresno Produce Inc.,JALAPENO,JALAPENO,40.0,$0.60,24.00,Jalapeno peppers,Peppers,Fresh vegetables,Food Beverage and Tobacco Products
1,10/18/2012,4500156192,Other Goods,Informal Competitive,"Corrections and Rehabilitation, Department of",PETER GIAMMANCO,produce,"red apples, banana,",1.0,$12587.05,12587.05,Ida red apples,Apples,Fresh fruits,Food Beverage and Tobacco Products
2,10/17/2012,4500156124,Other Goods,Fair and Reasonable,Correctional Health Care Services,OSHA Review Inc,magazine,magazine,1.0,$199.00,199.00,Magazines,Printed publications,Printed media,Published Products
3,10/24/2012,S2556056,Other Goods,Informal Competitive,"Parks & Recreation, Department of",Agco Hay LLC,hay,Bale's of rice straw,1000.0,$4.95,4950.00,Hay,Livestock feed,Animal feed,Live Plant and Animal Material and Accessories...
4,11/14/2012,4500159228,Other Goods,Informal Competitive,"Corrections and Rehabilitation, Department of",Prison Industry Authority,COFFEE,INSTANT COFFEE AND BULK,14686.5,$1.00,14686.50,Coffee,Coffee and tea,Beverages,Food Beverage and Tobacco Products

In [2]:
# Let's see the total price sum of the order number 018H2015
po_sum = df[df["Purchase Order Number"] == "018H2015"]["Total Price"].sum()
po_sum

# The sum of the order 018H2015 was 1245.04 dollars.

np.float64(1245.0400000000002)

In [3]:
# Let's see the item name and description for order 3176273
df[df["Purchase Order Number"] == "3176273"][["Item Name", "Item Description"]]

# Item name was PC Desktop and the description was HP Prodesk 600.

      Item Name Item Description
103  PC Desktop   HP Prodesk 600

In [5]:
# Let's see what the 5 most common departments are:
df["Department Name"].value_counts().head(5)

# We can see the 5 most common deparments under:

Department Name
Corrections and Rehabilitation, Department of    10858
Correctional Health Care Services                 6591
Water Resources, Department of                    4566
Forestry and Fire Protection, Department of       4513
State Hospitals, Department of                    4258
Name: count, dtype: int64